
emotional_keywords = [
    "tired",
    "so tired",
    "exhausted",
    "overwhelmed",
    "stressed",
    "hopeless",
    "worthless",
    "alone",
    "lonely",
    "isolated",
    "can't sleep",
    "crying",
    "feel numb",
    "feel empty",
    "life is hard",
    "nothing matters",
    "can't take it",
    "want to disappear",
    "want to die",
    "broken",
    "lost",
    "hurt",
    "pain",
    "suffering",
    "panic",
    "anxious",
    "depressed",
    "done with everything",
    "feel hopeless",
    "feel useless",
    "too much to handle",
    "so sad",
    "can't keep going",
    "burned out",
    "drained",
    "overthinking",
    "i'm not okay",
    "everything hurts",
    "wish i could disappear",
    "can't deal",
    "life is meaningless",
    "died",
    "die"
]
depression_keywords = [
    "sad",
    "depressed",
    "hopeless",
    "tired",
    "exhausted",
    "stressed",
    "overwhelmed",
    "lonely",
    "anxious",
    "can't do anything anymore",
    "I want to disappear",
    "I feel worthless",
    "alone",
    "pain",
    "suffering",
    "crying",
    "tears",
    "broken",
    "lost",
    "empty",
    "numb",
    "hurt",
    "panic"
]